# Generated by Django 2.1rc1 on 2018-08-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dislike',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='viewed',
            field=models.TextField(null=True),
        ),
    ]
